// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BudgetoidDbContext))]
    [Migration("20260901092459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("name");

                    b.Property<byte[]>("NameKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("name_key");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("opening_balance");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("BudgetId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("IX_accounts_budget_id_name_key");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_accounts_name_key_length", "length(name_key) = 32");

                            t.HasCheckConstraint("CK_accounts_name_length", "length(name) between 29 and 1024");

                            t.HasCheckConstraint("CK_accounts_name_version", "substring(name from 1 for 1) = '\\x01'::bytea");

                            t.HasCheckConstraint("CK_accounts_opening_balance", "abs(opening_balance) <= 1000000000");

                            t.HasCheckConstraint("CK_accounts_type", "type in ('Checking', 'Savings', 'Cash', 'CreditCard')");
                        });
                });

            modelBuilder.Entity("Domain.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("Name")
                        .HasColumnType("bytea")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_budgets_user_id_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("UserId", "Name"), false);

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("CK_budgets_name_length", "length(name) between 29 and 1024");

                            t.HasCheckConstraint("CK_budgets_name_version", "substring(name from 1 for 1) = '\\x01'::bytea");
                        });
                });

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_group_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_categories_budget_id_name");

                    b.HasIndex("CategoryGroupId", "BudgetId");

                    b.HasIndex("CategoryGroupId", "Position");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_categories_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("Domain.CategoryGroups.CategoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_category_groups_budget_id_name");

                    b.HasIndex("BudgetId", "Position");

                    b.ToTable("category_groups", null, t =>
                        {
                            t.HasCheckConstraint("CK_category_groups_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Currencies.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<int>("MinorUnit")
                        .HasColumnType("integer")
                        .HasColumnName("minor_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.HasKey("Code");

                    b.ToTable("currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_currencies_code", "code ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_currencies_minor_unit", "minor_unit between 0 and 4");
                        });

                    b.HasData(
                        new
                        {
                            Code = "AUD",
                            MinorUnit = 2,
                            Name = "Australian Dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Code = "BHD",
                            MinorUnit = 3,
                            Name = "Bahraini Dinar",
                            Symbol = "BD"
                        },
                        new
                        {
                            Code = "CAD",
                            MinorUnit = 2,
                            Name = "Canadian Dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Code = "CHF",
                            MinorUnit = 2,
                            Name = "Swiss Franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            Code = "EUR",
                            MinorUnit = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "GBP",
                            MinorUnit = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "JPY",
                            MinorUnit = 0,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "KWD",
                            MinorUnit = 3,
                            Name = "Kuwaiti Dinar",
                            Symbol = "KD"
                        },
                        new
                        {
                            Code = "NOK",
                            MinorUnit = 2,
                            Name = "Norwegian Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Code = "PLN",
                            MinorUnit = 2,
                            Name = "Polish Zloty",
                            Symbol = "zł"
                        },
                        new
                        {
                            Code = "SEK",
                            MinorUnit = 2,
                            Name = "Swedish Krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Code = "UAH",
                            MinorUnit = 2,
                            Name = "Ukrainian Hryvnia",
                            Symbol = "₴"
                        },
                        new
                        {
                            Code = "USD",
                            MinorUnit = 2,
                            Name = "US Dollar",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("Domain.Payees.Payee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_payees_budget_id_name");

                    b.ToTable("payees", (string)null);
                });

            modelBuilder.Entity("Domain.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credential_type");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("AK_sessions_id_user_id");

                    b.HasIndex("CredentialId", "UserId", "CredentialType")
                        .HasDatabaseName("IX_sessions_credential_id_user_id_credential_type");

                    b.HasIndex(new[] { "UserId" }, "IX_sessions_user_id")
                        .HasDatabaseName("IX_sessions_user_id");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_sessions_kind", "kind in ('full', 'locked')");

                            t.HasCheckConstraint("CK_sessions_kind_matches_credential", "(kind = 'full') = (credential_type in ('passkey', 'recovery_codes'))");

                            t.HasCheckConstraint("CK_sessions_lifetime", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("Domain.Sessions.SessionToken", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash");

                    b.HasIndex("SessionId", "UserId")
                        .HasDatabaseName("IX_session_tokens_session_id_user_id");

                    b.ToTable("session_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_session_tokens_token_hash_length", "length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("PayeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "BudgetId");

                    b.HasIndex("CategoryId", "BudgetId");

                    b.HasIndex("PayeeId", "BudgetId");

                    b.HasIndex("BudgetId", "Date", "CreatedAtUtc")
                        .IsDescending(false, true, true);

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_transactions_amount", "abs(amount) <= 1000000000");
                        });
                });

            modelBuilder.Entity("Domain.Users.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "UserId", "Type")
                        .HasName("AK_credentials_id_user_id_type");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("IX_credentials_provider_subject")
                        .HasFilter("type = 'federated'");

                    b.HasIndex(new[] { "UserId" }, "IX_credentials_user_id")
                        .HasDatabaseName("IX_credentials_user_id");

                    b.HasIndex(new[] { "UserId" }, "IX_credentials_user_id_federated")
                        .IsUnique()
                        .HasDatabaseName("IX_credentials_user_id_federated")
                        .HasFilter("type = 'federated'");

                    b.HasIndex(new[] { "UserId" }, "IX_credentials_user_id_recovery_codes")
                        .IsUnique()
                        .HasDatabaseName("IX_credentials_user_id_recovery_codes")
                        .HasFilter("type = 'recovery_codes'");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_credentials_provider", "provider is null or provider in ('google')");

                            t.HasCheckConstraint("CK_credentials_type", "type in ('passkey', 'federated', 'recovery_codes')");

                            t.HasCheckConstraint("CK_credentials_type_shape", "(type = 'federated' and provider is not null and subject is not null and length(subject) > 0) or (type = 'passkey' and provider is null and subject is null) or (type = 'recovery_codes' and provider is null and subject is null)");
                        });
                });

            modelBuilder.Entity("Domain.Users.PasskeyPublicKey", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<int>("Algorithm")
                        .HasColumnType("integer")
                        .HasColumnName("cose_algorithm");

                    b.Property<byte[]>("CoseKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key_cose");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credential_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("WebAuthnCredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("webauthn_credential_id");

                    b.HasKey("CredentialId");

                    b.HasIndex("WebAuthnCredentialId")
                        .IsUnique()
                        .HasDatabaseName("IX_passkey_public_keys_webauthn_credential_id");

                    b.HasIndex("CredentialId", "UserId", "CredentialType")
                        .HasDatabaseName("IX_passkey_public_keys_credential_id_user_id_credential_type");

                    b.ToTable("passkey_public_keys", null, t =>
                        {
                            t.HasCheckConstraint("CK_passkey_public_keys_cose_algorithm", "cose_algorithm in (-7, -257)");

                            t.HasCheckConstraint("CK_passkey_public_keys_credential_type", "credential_type = 'passkey'");

                            t.HasCheckConstraint("CK_passkey_public_keys_public_key_length", "length(public_key_cose) between 1 and 1024");

                            t.HasCheckConstraint("CK_passkey_public_keys_webauthn_credential_id_length", "length(webauthn_credential_id) between 16 and 1023");
                        });
                });

            modelBuilder.Entity("Domain.Users.PasskeySignatureCounter", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credential_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("signature_counter");

                    b.HasKey("CredentialId");

                    b.HasIndex("CredentialId", "UserId", "CredentialType")
                        .HasDatabaseName("IX_passkey_signature_counters_credential_id_user_id_credential_type");

                    b.HasIndex(new[] { "UserId" }, "IX_passkey_signature_counters_user_id")
                        .HasDatabaseName("IX_passkey_signature_counters_user_id");

                    b.ToTable("passkey_signature_counters", null, t =>
                        {
                            t.HasCheckConstraint("CK_passkey_signature_counters_credential_type", "credential_type = 'passkey'");

                            t.HasCheckConstraint("CK_passkey_signature_counters_value", "signature_counter >= 0 and signature_counter <= 4294967295");
                        });
                });

            modelBuilder.Entity("Domain.Users.RecoveryCodeHash", b =>
                {
                    b.Property<byte[]>("VerifierHash")
                        .HasColumnType("bytea")
                        .HasColumnName("verifier_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credential_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("VerifierHash");

                    b.HasIndex("CredentialId", "UserId", "CredentialType")
                        .HasDatabaseName("IX_recovery_code_hashes_credential_id_user_id_credential_type");

                    b.ToTable("recovery_code_hashes", null, t =>
                        {
                            t.HasCheckConstraint("CK_recovery_code_hashes_credential_type", "credential_type = 'recovery_codes'");

                            t.HasCheckConstraint("CK_recovery_code_hashes_verifier_hash_length", "length(verifier_hash) = 32");
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Users.WrappedAccountKeys", b =>
                {
                    b.Property<Guid>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("factor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credential_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("WrappedContentKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_content_key");

                    b.Property<byte[]>("WrappedIndexKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_index_key");

                    b.HasKey("FactorId")
                        .HasName("PK_wrapped_account_keys");

                    b.HasIndex("CredentialId", "UserId", "CredentialType")
                        .HasDatabaseName("IX_wrapped_account_keys_credential_id_user_id_credential_type");

                    b.HasIndex(new[] { "UserId" }, "IX_wrapped_account_keys_user_id")
                        .HasDatabaseName("IX_wrapped_account_keys_user_id");

                    b.ToTable("wrapped_account_keys", null, t =>
                        {
                            t.HasCheckConstraint("CK_wrapped_account_keys_credential_type", "credential_type in ('passkey', 'recovery_codes')");

                            t.HasCheckConstraint("CK_wrapped_account_keys_wrapped_content_key_length", "length(wrapped_content_key) = 61");

                            t.HasCheckConstraint("CK_wrapped_account_keys_wrapped_content_key_version", "get_byte(wrapped_content_key, 0) = 1");

                            t.HasCheckConstraint("CK_wrapped_account_keys_wrapped_index_key_length", "length(wrapped_index_key) = 61");

                            t.HasCheckConstraint("CK_wrapped_account_keys_wrapped_index_key_version", "get_byte(wrapped_index_key, 0) = 1");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.WebAuthnChallengeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ceremony")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ceremony");

                    b.Property<byte[]>("Challenge")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("challenge");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Challenge")
                        .IsUnique()
                        .HasDatabaseName("IX_webauthn_challenges_challenge");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_webauthn_challenges_expires_at_utc");

                    b.ToTable("webauthn_challenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_webauthn_challenges_ceremony", "ceremony in ('registration', 'authentication', 'reauthentication', 'account_registration')");

                            t.HasCheckConstraint("CK_webauthn_challenges_length", "length(challenge) = 32");

                            t.HasCheckConstraint("CK_webauthn_challenges_lifetime", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("Domain.Accounts.Account", b =>
                {
                    b.HasOne("Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Budgets.Budget", b =>
                {
                    b.HasOne("Domain.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.HasOne("Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CategoryGroups.CategoryGroup", null)
                        .WithMany()
                        .HasForeignKey("CategoryGroupId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_categories_category_groups_category_group_id_budget_id");
                });

            modelBuilder.Entity("Domain.CategoryGroups.CategoryGroup", b =>
                {
                    b.HasOne("Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Payees.Payee", b =>
                {
                    b.HasOne("Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Sessions.Session", b =>
                {
                    b.HasOne("Domain.Users.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId", "UserId", "CredentialType")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Sessions.SessionToken", b =>
                {
                    b.HasOne("Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_session_tokens_sessions");
                });

            modelBuilder.Entity("Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_transactions_accounts_account_id_budget_id");

                    b.HasOne("Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_categories_category_id_budget_id");

                    b.HasOne("Domain.Payees.Payee", null)
                        .WithMany()
                        .HasForeignKey("PayeeId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Users.Credential", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.PasskeyPublicKey", b =>
                {
                    b.HasOne("Domain.Users.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId", "UserId", "CredentialType")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_passkey_public_keys_credentials");
                });

            modelBuilder.Entity("Domain.Users.PasskeySignatureCounter", b =>
                {
                    b.HasOne("Domain.Users.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId", "UserId", "CredentialType")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_passkey_signature_counters_credentials");
                });

            modelBuilder.Entity("Domain.Users.RecoveryCodeHash", b =>
                {
                    b.HasOne("Domain.Users.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId", "UserId", "CredentialType")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_recovery_code_hashes_credentials");
                });

            modelBuilder.Entity("Domain.Users.WrappedAccountKeys", b =>
                {
                    b.HasOne("Domain.Users.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId", "UserId", "CredentialType")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wrapped_account_keys_credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
