using Application.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.Persistence.Configurations;

// Internal because WebAuthnChallengeRow is — see the remarks there. EF discovers it all the same:
// ApplyConfigurationsFromAssembly looks for a parameterless constructor, not for a public type.
internal sealed class WebAuthnChallengeConfiguration : IEntityTypeConfiguration<WebAuthnChallengeRow>
{
    // Pinned rather than left to EF's naming convention, which derives a name from the property names
    // and so moves the moment a property is renamed. A constraint name is what PostgreSQL reports and
    // what a caller matches a PostgresException against, so it has to outlive a rename.
    public const string CeremonyCheckName = "CK_webauthn_challenges_ceremony";

    public const string LifetimeCheckName = "CK_webauthn_challenges_lifetime";

    public const string LengthCheckName = "CK_webauthn_challenges_length";

    // A 23505 from this index means the same nonce was issued twice, which is the one duplicate that
    // must never be shrugged off — see the index itself below.
    public const string ChallengeIndexName = "IX_webauthn_challenges_challenge";

    private const string ExpiresAtIndexName = "IX_webauthn_challenges_expires_at_utc";

    // 32 bytes of entropy, the size WebAuthn's own guidance settles on. Exact rather than a floor: a
    // challenge is generated by one line of this system, so any other length is a bug in that line
    // rather than a caller's choice, and "between" would hide it.
    private const int ChallengeLength = 32;

    public void Configure(EntityTypeBuilder<WebAuthnChallengeRow> builder)
    {
        builder.ToTable("webauthn_challenges", table =>
        {
            // A CHECK rather than a native PostgreSQL enum type, exactly as on credentials.type and
            // sessions.kind: the conversion below already stores the member as text, so the check costs
            // nothing extra, while a PG enum turns adding a member into an ALTER TYPE dance.
            table.HasCheckConstraint(CeremonyCheckName, "ceremony in ('registration', 'authentication')");

            // A challenge whose expiry is at or before its creation was never live for an instant, and
            // so was never a challenge. The bound matters more here than on most tables: the expiry is
            // the only thing limiting how long a nonce can be replayed, and a row that reversed the two
            // would be one the sweep deletes but the verifier — reading "expires_at_utc > now()" —
            // never accepts, or the other way round if either comparison is ever written differently.
            table.HasCheckConstraint(LifetimeCheckName, "expires_at_utc > created_at_utc");

            // A short challenge is a guessable one, and guessing it is the whole attack the nonce
            // exists to prevent.
            table.HasCheckConstraint(LengthCheckName, $"length(challenge) = {ChallengeLength}");
        });

        builder.HasKey(challenge => challenge.Id);

        builder.Property(challenge => challenge.Id).HasColumnName("id");

        // No user_id column, and its absence is a decision rather than an omission. The authentication
        // ceremony issues a challenge before anybody has said who they are — that is what makes a
        // discoverable credential discoverable — so at the moment the row is written there is no owner
        // for a policy to key on. A nullable ownership column would not fix that: RLS on a NULL owner
        // fails closed, so the row would be invisible to the very request that has to read it back,
        // and RowLevelSecurityCoverage refuses a nullable ownership column outright. What guards this
        // table instead is that its rows say nothing about anybody: a random 32 bytes and two instants,
        // useless without the assertion that spends them.
        //
        // The consequence, for whoever writes the grants: this table is owned by no tenant, so it needs
        // an exemption argued on those grounds rather than a policy.
        builder.Property(challenge => challenge.Challenge)
            .HasColumnName("challenge")
            .HasColumnType("bytea")
            .IsRequired();

        // The vocabulary is written out once per direction, for the reason recorded on
        // CredentialConfiguration.Type: HasConversion<string>() would store the PascalCase member
        // names, and the case-insensitive Enum.Parse on the way back would accept "REGISTRATION" and
        // the numeric "0", neither of which the CHECK above allows. The switches sit in methods because
        // these arguments are expression trees, which cannot contain a switch expression.
        builder.Property(challenge => challenge.Ceremony)
            .HasConversion(
                ceremony => ToColumnValue(ceremony),
                value => FromColumnValue(value))
            .HasColumnName("ceremony")
            .HasMaxLength(20)
            .IsRequired();

        builder.Property(challenge => challenge.CreatedAtUtc)
            .HasColumnName("created_at_utc")
            .HasColumnType("timestamp with time zone")
            .IsRequired();

        builder.Property(challenge => challenge.ExpiresAtUtc)
            .HasColumnName("expires_at_utc")
            .HasColumnType("timestamp with time zone")
            .IsRequired();

        // The lookup key: the second message of a ceremony names the challenge and nothing else, so
        // this is the only way in. Unique because a nonce that could be stored twice is a nonce, and
        // spending one row would leave the other spendable.
        builder.HasIndex(challenge => challenge.Challenge)
            .IsUnique()
            .HasDatabaseName(ChallengeIndexName);

        // The sweep that deletes expired rows reads on this column and on nothing else. Without the
        // index that sweep is a sequential scan over a table whose whole purpose is to stay small,
        // which is the shape that quietly stops being run.
        builder.HasIndex(challenge => challenge.ExpiresAtUtc)
            .HasDatabaseName(ExpiresAtIndexName);
    }

    // The discard arm is unreachable from anything the application can produce: it means a member was
    // added to WebAuthnCeremony and nobody chose a spelling for it here, or an undeclared value was
    // cast into the enum. That is a caller handing the converter a value outside its declared range,
    // and the exception says so — the enum member, not the column, is what is wrong.
    private static string ToColumnValue(WebAuthnCeremony ceremony) => ceremony switch
    {
        WebAuthnCeremony.Registration => "registration",
        WebAuthnCeremony.Authentication => "authentication",
        _ => throw new ArgumentOutOfRangeException(
            nameof(ceremony),
            ceremony,
            $"No webauthn_challenges.ceremony spelling is defined for this {nameof(WebAuthnCeremony)} member."),
    };

    // A different failure from the one above, so a different exception: nothing was passed wrongly here
    // — the row itself holds a ceremony CK_webauthn_challenges_ceremony should have refused, which
    // makes it state the model says cannot exist rather than a bad argument. Anyone reading the message
    // needs the offending value, because finding the row is the only way to learn how it got written.
    private static WebAuthnCeremony FromColumnValue(string value) => value switch
    {
        "registration" => WebAuthnCeremony.Registration,
        "authentication" => WebAuthnCeremony.Authentication,
        _ => throw new InvalidOperationException(
            $"The webauthn_challenges.ceremony column holds '{value}', a value {CeremonyCheckName} "
            + "should have refused."),
    };
}
