# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy dotnet core project to Azure Function App - budgetoid-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "8.0.x" # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release ./Budgetoid --output ./output
          popd

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.5.1
        with:
          # Name of the Azure Function App
          app-name: bugetoid-app
          # Function app slot to be deployed to
          slot-name: staging
          # Publish profile (*.publishsettings) file contents with web deploy secrets
          publish-profile: ${{ env.AZURE_BUDGETOID_PUBLISH_PROFILE_STAGING }}
                
